version: "3.9" 
services:
   web:
       build: .
       ports:
           - "10000:10000"
       environment:
           MONGODB_URI:mongodb+srv://keshav1:keshav1@cluster0.sjkrk.mongodb.net/myFirstDatabase?retryWrites=true&w=majority